#!/bin/bash

CURRENT_DIR=$PWD
WORK_DIR=$PWD/workdir

if [ ! -d $WORK_DIR ]; then
   mkdir -p $WORK_DIR
fi

if [ ! -e etc/config.conf ] || [ ! -e etc/common.sh ] || [ ! -e etc/pipeline.sh ] then
   echo "some files missing under \/etc..."
   ecit 1
fi

source etc/config.conf
source etc/common.sh
source etc/pipeline.sh

git-clone-concourse-docker
concourse-docker-key-generation
cert-key-generation
docker-compose-process
run-concourse
pipeline-repo-prepare
cluster-repo-prepare
pipeline-build
