#!/bin/bash

CURRENT_DIR=$PWD
WORK_DIR=$PWD/workdir
if [ ! -d $WORK_DIR ]; then mkdir -p $WORK_DIR ; fi
if [ ! -e etc/config.conf ]; then
   echo "you are not at the right dirtory yet..."
   exit 1
else
   source etc/config.conf
fi
if [ ! -e etc/common.sh ]; then
   echo "the etc\/common.sh file is missing..."
   exit 1
else
   source etc/common.sh
fi
if [ ! -e etc/pipeline.sh ]; then
   echo " the etc\/pipeline.sh file is missing..."
   exit 1
else
   source etc/pipeline.sh
fi


git-clone-concourse-docker
concourse-docker-key-generation
cert-key-generation
docker-compose-process
run-concourse
pipeline-repo-prepare
cluster-repo-prepare
pipeline-build
